/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.app.component;

import com.app.util.UppercaseDocumentFilter;
import java.awt.AlphaComposite;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import javax.swing.text.AbstractDocument;

/**
 *
 * @author LENOVO
 */
public class PanelVerifyMail extends javax.swing.JPanel {

    /**
     * Creates new form PanelVerifyMail
     */
    
    private ActionListener eventVerify;
    private ActionListener eventCancel;
    
    
    public PanelVerifyMail(ActionListener eventVerify, ActionListener eventCancel) {
        initComponents();
        
        this.eventVerify = eventVerify;
        this.eventCancel = eventCancel;
        buttonVerify.addActionListener(eventVerify);
        buttonCancel.addActionListener(eventCancel);
        
        
        setOpaque(false);
        setFocusCycleRoot(true);
        setVisible(false);
        setFocusable(true);
        addMouseListener(new MouseAdapter() {});
        txVerifyCode.setFont(new java.awt.Font("sansserif", 1, 20));
        ((AbstractDocument)txVerifyCode.getDocument()).setDocumentFilter(new UppercaseDocumentFilter(7));
    }
    
    @Override
    public void setVisible(boolean aFlag) {
        super.setVisible(aFlag); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
        if (aFlag) {
            txVerifyCode.grabFocus();
            txVerifyCode.setText("");
        }
    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
        Graphics2D g2 = (Graphics2D) g;
        g2.setColor(new Color(50,50,50));
        g2.setComposite(AlphaComposite.getInstance(AlphaComposite.SRC_OVER, 0.5f));
        g2.fillRect(0, 0, getWidth(), getHeight());
        g2.setComposite(AlphaComposite.SrcOver);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customPanel1 = new com.app.component.CustomPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txVerifyCode = new com.app.component.CustomTextField();
        buttonCancel = new com.app.component.CustomButton();
        buttonVerify = new com.app.component.CustomButton();

        customPanel1.setBorderColor(new java.awt.Color(0, 153, 0));
        customPanel1.setBorderSize(0);
        customPanel1.setRadius(20);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Check your mail to get verify code");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Verify Code");

        txVerifyCode.setForeground(new java.awt.Color(102, 102, 102));
        txVerifyCode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txVerifyCode.setText("A1B3C4");
        txVerifyCode.setColor(new java.awt.Color(245, 245, 245));
        txVerifyCode.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        txVerifyCode.setRadius(10);

        buttonCancel.setForeground(new java.awt.Color(111, 111, 111));
        buttonCancel.setText("Cancel");
        buttonCancel.setBorderColor(new java.awt.Color(111, 111, 111));
        buttonCancel.setColorClick(new java.awt.Color(222, 222, 222));
        buttonCancel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        buttonCancel.setForegroundClick(new java.awt.Color(0, 0, 0));
        buttonCancel.setForegroundColor(new java.awt.Color(111, 111, 111));
        buttonCancel.setForegroundOver(new java.awt.Color(111, 111, 111));
        buttonCancel.setRadius(30);

        buttonVerify.setText("Verify");
        buttonVerify.setColorClick(new java.awt.Color(222, 222, 222));
        buttonVerify.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonVerify.setForegroundClick(new java.awt.Color(0, 0, 0));
        buttonVerify.setForegroundColor(new java.awt.Color(0, 0, 0));
        buttonVerify.setForegroundOver(new java.awt.Color(0, 0, 0));
        buttonVerify.setRadius(30);

        javax.swing.GroupLayout customPanel1Layout = new javax.swing.GroupLayout(customPanel1);
        customPanel1.setLayout(customPanel1Layout);
        customPanel1Layout.setHorizontalGroup(
            customPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(customPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(customPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(customPanel1Layout.createSequentialGroup()
                        .addComponent(buttonVerify, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txVerifyCode, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(customPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(customPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        customPanel1Layout.setVerticalGroup(
            customPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txVerifyCode, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(customPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonVerify, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
            .addGroup(customPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(customPanel1Layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(jLabel2)
                    .addContainerGap(192, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(customPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(customPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.app.component.CustomButton buttonCancel;
    private com.app.component.CustomButton buttonVerify;
    private com.app.component.CustomPanel customPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private com.app.component.CustomTextField txVerifyCode;
    // End of variables declaration//GEN-END:variables
}
